# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.25

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /snap/cmake/1204/bin/cmake

# The command to remove a file.
RM = /snap/cmake/1204/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alse/Documents/sofware1

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alse/Documents/sofware1

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/snap/cmake/1204/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/snap/cmake/1204/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alse/Documents/sofware1/CMakeFiles /home/alse/Documents/sofware1//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alse/Documents/sofware1/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sofware1.bin

# Build rule for target.
sofware1.bin: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sofware1.bin
.PHONY : sofware1.bin

# fast build rule for target.
sofware1.bin/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sofware1.bin.dir/build.make CMakeFiles/sofware1.bin.dir/build
.PHONY : sofware1.bin/fast

src/config_tty.o: src/config_tty.cpp.o
.PHONY : src/config_tty.o

# target to build an object file
src/config_tty.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sofware1.bin.dir/build.make CMakeFiles/sofware1.bin.dir/src/config_tty.cpp.o
.PHONY : src/config_tty.cpp.o

src/config_tty.i: src/config_tty.cpp.i
.PHONY : src/config_tty.i

# target to preprocess a source file
src/config_tty.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sofware1.bin.dir/build.make CMakeFiles/sofware1.bin.dir/src/config_tty.cpp.i
.PHONY : src/config_tty.cpp.i

src/config_tty.s: src/config_tty.cpp.s
.PHONY : src/config_tty.s

# target to generate assembly for a file
src/config_tty.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sofware1.bin.dir/build.make CMakeFiles/sofware1.bin.dir/src/config_tty.cpp.s
.PHONY : src/config_tty.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sofware1.bin.dir/build.make CMakeFiles/sofware1.bin.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sofware1.bin.dir/build.make CMakeFiles/sofware1.bin.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sofware1.bin.dir/build.make CMakeFiles/sofware1.bin.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/participant.o: src/participant.cpp.o
.PHONY : src/participant.o

# target to build an object file
src/participant.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sofware1.bin.dir/build.make CMakeFiles/sofware1.bin.dir/src/participant.cpp.o
.PHONY : src/participant.cpp.o

src/participant.i: src/participant.cpp.i
.PHONY : src/participant.i

# target to preprocess a source file
src/participant.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sofware1.bin.dir/build.make CMakeFiles/sofware1.bin.dir/src/participant.cpp.i
.PHONY : src/participant.cpp.i

src/participant.s: src/participant.cpp.s
.PHONY : src/participant.s

# target to generate assembly for a file
src/participant.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sofware1.bin.dir/build.make CMakeFiles/sofware1.bin.dir/src/participant.cpp.s
.PHONY : src/participant.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... sofware1.bin"
	@echo "... src/config_tty.o"
	@echo "... src/config_tty.i"
	@echo "... src/config_tty.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/participant.o"
	@echo "... src/participant.i"
	@echo "... src/participant.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

